### PR TITLE
Fix read functions to set resource based on response

### PR DESCRIPTION
**Pull request by mcmluk-monster**
The PR is to fix the read functions of all the resources so that fields obtained from the API call are set to the resource state. 

New corresponding flatten functions are added as the data sources and resources have different schemas.

### CODE REVIEW

**Comment by greatestusername-splunk** [comment]
Thank you for contributing this back!

Http check read looks and works great!

One strange thing I'm seeing is that the API check seems to always think there has been a change even when there hasn't been. Are you seeing the same on your side with API check resources?

Example plan I'm getting for a brand new applied API check after running a `terraform apply`  
Doing some troubleshooting on my side to see what might be causing the constant nulls

```
# synthetics_create_api_check_v2.api_v2_foo_check will be updated in-place
  ~ resource "synthetics_create_api_check_v2" "api_v2_foo_check" {
        id = "212429"

      - test {
          - active              = true -> null
          - device_id           = 1 -> null
          - frequency           = 5 -> null
          - location_ids        = [
              - "aws-us-east-1",
            ] -> null
          - name                = "Terraform - Api V2 Checkaroo" -> null
          - scheduling_strategy = "round_robin" -> null

          - requests {
              - configuration {
                  - body           = <<-EOT
                        \'{"alert_name":"the service is down","url":"https://foo.com/bar"}\'
                    EOT -> null
                  - headers        = {
                      - "Accept" = "application/json"
                      - "xFoo"   = "bar"
                    } -> null
                  - name           = "Get products" -> null
                  - request_method = "GET" -> null
                  - url            = "https://dummyjson.com/products" -> null
                }
              - setup {
                  - extractor = "$.foo" -> null
                  - name      = "First setup step" -> null
                  - source    = "{\\'foo\\': \\'bar\\'}" -> null
                  - type      = "extract_json" -> null
                  - variable  = "myVariable" -> null
                }
              - validations {
                  - actual     = "{{response.code}}" -> null
                  - comparator = "equals" -> null
                  - expected   = "200" -> null
                  - name       = "My validation step" -> null
                  - type       = "assert_numeric" -> null
                }
            }
        }
      + test {
          + active              = true
          + device_id           = 1
          + frequency           = 5
          + location_ids        = [
              + "aws-us-east-1",
            ]
          + name                = "Terraform - Api V2 Checkaroo"
          + scheduling_strategy = "round_robin"

          + requests {
              + configuration {
                  + body           = <<-EOT
                        \'{"alert_name":"the service is down","url":"https://foo.com/bar"}\'
                    EOT
                  + headers        = {
                      + "Accept" = "application/json"
                      + "x-foo"  = "bar"
                    }
                  + name           = "Get products"
                  + request_method = "GET"
                  + url            = "https://dummyjson.com/products"
                }
              + setup {
                  + extractor = "$.foo"
                  + name      = "First setup step"
                  + source    = "{\\'foo\\': \\'bar\\'}"
                  + type      = "extract_json"
                  + variable  = "myVariable"
                }
              + validations {
                  + actual     = "{{response.code}}"
                  + comparator = "equals"
                  + expected   = "200"
                  + name       = "My validation step"
                  + type       = "assert_numeric"
                }
            }
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Review by greatestusername-splunk — COMMENTED** [review]
Seeing an error `Error: Invalid address to set: []string{"test", "0", "type"}`

Which can be fixed by adding `type` into the schema here as a computed value.
```
"type": {
    Type: schema.TypeString,
    Computed: true,
},
```

**Comment by greatestusername-splunk** [comment]
Many thanks for this contribution! 
I'm curious if you're seeing any weirdness with browser checks when implementing that read and flatten? Specifically always showing the resource as "changed" and tf apply wanting to update it every run.

I think your PR has uncovered a couple things that may have changed (specifically with browser tests) since last go client update. Also some weird parsing issues with hyphens I'm trying to track down that didn't exist a couple months ago.

Your changes for port check, http check, variables, locations all work and look fine though! API check looks good other than the hyphen parsing I mentioned. Lets talk about how we can get those in and merged. 

Then I (or we if you're interested) can get the client stuff for browser checks worked out.

Thanks again for contributing!

**Comment by mcmluk-monster** [comment]
I noticed the interesting behaviour with the API Check as well. I was thinking it might actually be behaviour within the API itself. I directly made a POST request, with the hyphened headers
```
"requests": [
                    {
                        "configuration": {
                            "body": "test",
                            "headers": {
                                "Accept": "application/json",
                                "x-foo": "bar"
                            },
                            "name": "Get products",
                            "requestMethod": "GET",
                            "url": "https://dummyjson.com/products"
                        }
                    }
                ]
```
and still get a response with similar behaviour as seen in the terraform response
```
		"requests": [
			{
				"configuration": {
					"name": "Get products",
					"url": "https://dummyjson.com/products",
					"requestMethod": "GET",
					"headers": {
						"Accept": "application/json",
						"xFoo": "bar"
					},
					"body": "test"
				},
```

which makes me think it's not as much an issue with the provider or the go client at all.

Still looking into the browser check as well. I had started with API Checks and HTTP Checks first, but thought I might as well add in the same logic into the rest of the resources too which may have opened a can of worms

**Comment by greatestusername-splunk** [comment]
Yeah I'm noticing that as well after testing just using curl. That is definitely new behavior.
I've brought that up with the synthetics engineering team and will keep you in the loop as I find out more.

That said, I think we could probably merge the other resources now pretty quickly if you wanted to do two PRs? 

One for http, variable, location, etc
And a second for Browser Checks / API Checks? Thoughts?

Again, I really appreciate your contribution and for pointing this all out!

**Comment by greatestusername-splunk** [comment]
Update regarding API tests issue with custom headers and hyphenation a fix is being reviewed and hopefully released ASAP.

**Comment by greatestusername-splunk** [comment]
Linking a PR with underlying changes needed for this as well as the actual reads
https://github.com/splunk/terraform-provider-synthetics/pull/22

**Comment by greatestusername-splunk** [comment]
PR #22 merged and released containing changes from this PR.

Closing.

**Pull request closed without merging**
