### PR TITLE
add validations to http check v2

### PR DESCRIPTION
**Pull request by mcmluk-monster**
This PR aims to add the validations field into the http check v2 resource after it has been added to the synthetics client

### CODE REVIEW

**Comment by greatestusername-splunk** [comment]
Thanks for your contributions @mcmluk-monster! posted this same message on your PR to the synthetics client repo. Same deal here.

I've just added [CLA](https://github.com/splunk/terraform-provider-synthetics/blob/main/CLA.md) (agreement to the oss license) and [COC](https://github.com/splunk/terraform-provider-synthetics/blob/main/CODE_OF_CONDUCT.md) (code of conduct) documents to this PR.

Please give them a look and respond in a comment to this PR with

I have read the CLA Document and I hereby sign the CLA
I have read the Code of Conduct and I hereby accept the Terms
I'll be setting up an action to check and remind for this soon but was asked to get this agreement manually in the mean time.

Thanks again and its great to have your contributions! Once the client changes are in we can get these changes going! 🚀

**Comment by mcmluk-monster** [comment]
I have read the CLA Document and I hereby sign the CLA
I have read the Code of Conduct and I hereby accept the Terms

**Comment by mcmluk-monster** [comment]
Since https://github.com/splunk/syntheticsclient/pull/9 is merged, we can add the validations into the http check now

**Review by greatestusername-splunk — APPROVED** [review]
lgtm

**Pull request merged**
