### PR TITLE
SYN-3798: add last_run_status and last_run_at to /tests/ response

### PR DESCRIPTION
**Pull request by bchhay-splunk**
Resolves #ISSUE_NUMBER

----

### Before the change?

* need: https://github.com/splunk/syntheticsclient/pull/15 and https://github.com/splunk/syntheticsclient/pull/16

### After the change?

* 

### Pull request checklist 
- [ ] Acceptance Tests have been updated, run (`make testacc`), and pasted in this PR (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

#### Acceptance Test Output

```

```

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

----

### CODE REVIEW

**Comment by greatestusername-splunk** [comment]
Reviewing changes in synthetics client

**Comment by greatestusername-splunk** [comment]
https://github.com/splunk/syntheticsclient/releases/tag/v2.0.6
Should be released and usable for this stuff. Thank you for contributing!

**Comment by bchhay-splunk** [comment]
@greatestusername-splunk i pulled in the vendor changes for the newest tag. should be good to go now!

**Comment by greatestusername-splunk** [comment]
Passes acceptance test
```
terraform-provider-synthetics 12:11> make testacc
TF_ACC=1 go test $(go list ./... | grep -v 'vendor')  -timeout 120m   | sed '/X-Sf-Token/d'
?       github.com/splunk/terraform-provider-synthetics [no test files]
ok      github.com/splunk/terraform-provider-synthetics/synthetics      38.343s
```

**Review by greatestusername-splunk — APPROVED** [review]
LGTM

Only updates datasources and adds to structures

**Pull request merged**
